### ISSUE TITLE
Need Nottification Popup Handler within the the Export Code for Collegboard TSI

### ISSUE THREAD

**Issue by Richard-Barrett** [Richard-Barrett/ITDataServicesInfra#15]
So occasionally a popup window will pop up showing us notifciations. 
As it currently stands we do not have any popup window handling within the code, and as such we need to include a handle method or function to detect when a popup occurs after initial login. 
As it stands there are no other known pop-ups that occur periodically. 
Furthermore, there is nothing that scrapes all of this and sends us an email in regards to the notifications. Perhaps this could be a feature request?

Current Pop Up Window that Occasionally Plagues Us:
```<div id="whatsNewContainer" role="contentinfo">
                  <div class="widget-body">
                     <div id="whatsNewData"><p style="text-align:center"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="font-size:18px"><strong>Last update - January 29, 2020</strong></span></span></p>

<p style="text-align:center"><span style="font-family:lucida sans unicode,lucida grande,sans-serif; font-size:16px">&nbsp;</span></p>

<p style="text-align:center"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="font-size:18px"><u><strong>Upcoming System Maintenance</strong></u></span></span></p>

<div><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">A standard system maintenance window is scheduled for <strong>Sunday, February 9</strong> starting at 9:00 PM EST and ending on Monday, February 10 at 1:00 AM EST&nbsp;<strong>(4 hours total)</strong>.&nbsp;<span style="color:#FF0000"><strong>Please avoid using the system at this time.</strong></span></span></span></div>

<div>
<hr></div>

<div style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, Helvetica, Arial, sans-serif; font-size: 14px; text-align: center;"><u><span style="font-size:18px"><strong><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Contact Your IT Staff: Windows OS Update</span></strong></span></u></div>

<div style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">&nbsp;</div>

<div style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, Helvetica, Arial, sans-serif; font-size: 14px;"><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">REMINDER:&nbsp;Effective Jan 1, 2020, ACCUPLACER will no longer support the Windows 7, Windows 8, and Windows 8.1 Operating System (OS).&nbsp; If your institution has these operating systems on machines used for ACCUPLACER testing, you'll need to engage with your IT staff to upgrade to the latest version of Windows to ensure continuity of test administrations.&nbsp;</span></span></div>

<hr>
<p style="text-align:center">&nbsp;</p>

<p style="text-align:center"><u><strong><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">“Access to this account is set to expire” Message—Contact your IA</span></span></strong></u></p>

<p><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">To enhance account security, last September we added a requirement that ACCUPLACER user accounts remain active for no longer than 365 days at a time. If you begin to see notifications at the top of the Welcome screen that state “Access to this account is set to expire…” please contact your Institution Administrator to have your account access date extended.</span></span></p>

<p><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#B22222"><strong>Note:</strong></span> This is separate from the requirement to renew your ACTA certification. You will receive a similar notification reminding you to renew your ACTA 30 days before your current certification expires.</span></span></p>

<hr>
<p style="text-align:center">&nbsp;</p>

<p style="text-align:center"><u><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><strong>New Multiple Factors Capabilities Now Available</strong></span></span></u></p>

<p><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">College Board developed a more robust method of incorporating multiple factors into your placement decisions. The new interactive multiple factors composite tool will assist institutions in creating sound composite scores by placing all factors on the next-generation scoring scale (200–300).</span></span></p>

<p><span style="font-size:16px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Please refer to the March ACCUGRAM for steps you can take now to prepare for the tool’s use and consider <a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcollegeboardtraining.webex.com%2Fmw3300%2Fmywebex%2Fdefault.do%3Fnomenu%3Dtrue%26siteurl%3Dcollegeboardtraining%26service%3D6%26rnd%3D0.41207987219230147%26main_url%3Dhttps%253A%252F%252Fcollegeboardtraining.webex.com%252Fec3300%252Feventcenter%252Fprogram%252FprogramDetail.do%253FtheAction%253Ddetail%2526internalProgramTicket%253D4832534b00000004f3e355bee5d65a78b5dc7f43e693ab8d4d1c748c82067d9fa7be10f54b408795%2526siteurl%253Dcollegeboardtraining%2526internalProgramTicketUnList%253D4832534b00000004f3e355bee5d65a78b5dc7f43e693ab8d4d1c748c82067d9fa7be10f54b408795%2526cProgViewID%253D477672%2526PRID%253D574f578f537239f5393e0d1f2fc64cc7&amp;data=02%7C01%7Csherz%40collegeboard.org%7C58bedecb1624404b99e508d6b1f9d2cd%7C7530bdedfd6e4f58b5d2ea681eb07663%7C0%7C0%7C636892083878437802&amp;sdata=I6crBOgKhttpDZ1QYrQ62XhvfUKITwVegPYhu2jooW4%3D&amp;reserved=0" target="_blank">registering</a> for a webinar session to learn more about it.</span></span></p>
</div>
                  </div>
               </div>```

The Checkbox Button:
```
Notifications Checkbox:
<input type="checkbox" id="blockWhatsnewModal" value="Y" name="blockWhatsnewModal" class="ng-valid ng-dirty ng-valid-parse ng-touched ng-not-empty" ng-true-value="'Yes'" ng-false-value="'No'" ng-model="whatsNew.checkValue" style="">
Checkbox XPATH
//*[@id="blockWhatsnewModal"]
```

The Notifications Submission Button 
```
<button type="button" ng-show="updateWhatsNewFlag == 'failure'" translate="submit" class="btn btn-sm btn-success ng-scope" ng-click="updateShowWhatsNewFlag()" style="">Submit</button>

XPATH
//*[@id="whatsNewModal"]/div/div/div/div[2]/div[3]/button[1]
```
Hit Close Button:
```
Element:
<button type="button" class="btn btn-default ng-scope" data-dismiss="modal" ng-click="clearMessages()" translate="common.btn.close">Close</button>
Button XPATH: //*[@id="whatsNewModal"]/div/div/div/div[2]/div[3]/button[2]

```

**Comment by Richard-Barrett** [comment]
<button type="button" ng-show="updateWhatsNewFlag == 'failure'" translate="submit" class="btn btn-sm btn-success ng-scope" ng-click="updateShowWhatsNewFlag()" style="">Submit</button>

**Comment by Richard-Barrett** [comment]
Here is the overall code to click the submit button on a pop-up window
`<button type="button" ng-show="updateWhatsNewFlag == 'failure'" translate="submit" class="btn btn-sm btn-success ng-scope" ng-click="updateShowWhatsNewFlag()" style="">Submit</button>`

**Comment by Richard-Barrett** [comment]
Here is the checkbox you have to select for the pop-up window. 
`<label class="checkbox ng-binding" ng-show="updateWhatsNewFlag == 'failure'" style="">
                  <input type="checkbox" id="blockWhatsnewModal" value="Y" name="blockWhatsnewModal" class="ng-valid ng-dirty ng-valid-parse ng-touched ng-empty" ng-true-value="'Yes'" ng-false-value="'No'" ng-model="whatsNew.checkValue" style="">
                  <i></i>
                  Do not display this notification again until a new notice is posted.
               </label>`

**Comment by Richard-Barrett** [comment]
The Close button must be submitted afterwards:
`<button type="button" class="btn btn-default ng-scope" data-dismiss="modal" ng-click="clearMessages()" translate="common.btn.close">Close</button>`

General Procedure to Handle Pop-up Workflows: 
- 1. Click Checkbox
- 2. Hit Submit button
- 3. Hit Close Button

**Comment by Richard-Barrett** [comment]
Here is the overall trace back for such a button
`Traceback (most recent call last):
  File ".\secret_collegeboard_tsi_export.py", line 94, in <module>
    element.click();
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="#">...</a> is not clickable at point (110, 382). Other element would receive the click: <div class="modal fade in" id="whatsNewModal" tabindex="-1" role="dialog" aria-labelledby="whatsNewModalLabel" style="display: block; padding-right: 17px;">...</div>
  (Session info: chrome=80.0.3987.116)`
