### ISSUE TITLE
Code Issue for Chrome Driver Version

### ISSUE THREAD

**Issue by Richard-Barrett** [Richard-Barrett/ITDataServicesInfra#16]
Traceback (most recent call last):
  File ".\collegboard_tsi_export.py", line 51, in <module>
    browser = webdriver.Chrome("C:\Program Files (x86)\Google\Chrome\chromedriver.exe")
  File "C:\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78

Driver issue with chrome versioning need a unit test made to help conditons

**Comment by Richard-Barrett** [comment]
Basically we need to get a conditional statement that determines what version of chrome you are using and then make it actually download the file if version requirements are not met within a specified platform.
