### ISSUE TITLE
Loading Query Data into the Forms

### ISSUE THREAD

**Issue by Richard-Barrett** [Richard-Barrett/ITDataServicesInfra#2]
I am trying to load in the query data into this field automatically based off of a pre-defined query that has been established within the actual interface. I am getting the following output from the the collegeboard_tsi_export.py 

`Traceback (most recent call last):
  File ".\collegboard_tsi_export.py", line 77, in <module>
    element.click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <select class="form-control ng-pristine ng-untouched ng-valid ng-not-empty-add ng-animate ng-empty-remove ng-not-empty ng-not-empty-add-active ng-empty-remove-active" name="queryId" ng-model="searchCriteria.queryId" ng-change="loadSavedQuery(searchCriteria.queryId,searchCriteria.levelTypeId)" id="loadSavedQueryCustomReport" data-ng-animate="2" style="">...</select> is not clickable at point (727, 287). Other element would receive the click: <div id="cover" ng-class="{'coverOverModal': modalLodaingCover }" style="display: block;"></div>
  (Session info: chrome=79.0.3945.130)`

The error stems from this code that I am trying to use within the script:
`# Load Current Year Query
element = WebDriverWait(browser, 20).until(
        EC.element_to_be_clickable((By.NAME, "queryId")))
element.click()`
Furthermore, I am trying to select the 3rd index as a selection option from the drop down menu.
Here is the element I am trying to manipulate:
`<select class="form-control ng-pristine ng-valid ng-not-empty ng-touched" name="queryId" ng-model="searchCriteria.queryId" ng-change="loadSavedQuery(searchCriteria.queryId,searchCriteria.levelTypeId)" id="loadSavedQueryCustomReport" style="">
                     <option ng-repeat="query in queryList" value="SelectOne" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope" selected="selected" style="">-Select One-</option><option ng-repeat="query in queryList" value="5036589" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">All TSI Scores 2018</option><option ng-repeat="query in queryList" value="4962694" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">All TSI Scores 2019</option><option ng-repeat="query in queryList" value="5450792" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">All TSI Scores 2020</option><option ng-repeat="query in queryList" value="2339892" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">Annual Archive</option><option ng-repeat="query in queryList" value="5381192" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">Automated All TSI Scores 2019</option><option ng-repeat="query in queryList" value="2339781" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">Historical All</option><option ng-repeat="query in queryList" value="5368239" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">Historical All TSI Table - Windows COMMA,CSV,WEB</option><option ng-repeat="query in queryList" value="4960265" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">TSI Math Scores</option><option ng-repeat="query in queryList" value="4960214" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">TSI Reading Scores 2019</option><option ng-repeat="query in queryList" value="4960369" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">TSI Write Placer 2019</option><option ng-repeat="query in queryList" value="4960340" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">TSI Writing Scores 2019</option><option ng-repeat="query in queryList" value="4960433" ng-selected="searchCriteria.queryId==query.reportSavedQueryId" class="ng-binding ng-scope">TSI Writing Scores_2019</option>
                  </select>`

**Comment by Richard-Barrett** [comment]
Going to go ahead and make another request within the Stackoverflow community.

**Comment by Richard-Barrett** [comment]
Tried too update the overall issue with the the code looking like this

`# Load Current Year Query
load_query = Select(browser.find_element_by_class_name("form-control ng-pristine ng-valid ng-not-empty ng-touched"))
load_query.select_by_value("3")

# Report Description
description = browser.find_element_by_id('reportDescriptionCustomReport')
description.send_keys("CustomNameNeedsFormatting")`

However, I got this traceback:
`Traceback (most recent call last):
  File ".\collegboard_tsi_export.py", line 75, in <module>
    load_query = Select(browser.find_element_by_class_name("form-control ng-pristine ng-valid ng-not-empty ng-touched"))
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".form-control ng-pristine ng-valid ng-not-empty ng-touched"}
  (Session info: chrome=79.0.3945.130)`

**Comment by Richard-Barrett** [comment]
The Issue has been solved, however, I don't think it is dynamic yet. As such I will need to probably look into making a sub-module or process that will update a query and save it to be a current year.

**Comment by Richard-Barrett** [comment]
The issue has been resolved.
